### PR TITLE
fix: support React functional component - functional component doesnot have instance

### PR DESCRIPTION
**Pull request by newying61**
Add check for React component instance.
For functional component, the instance in ReactDOM.render callback is null.

### CODE REVIEW

**Review by cjol — APPROVED** [review]
I have no authority but this looks like a simple change and looks like it works well.

**Review by BendaCoding — APPROVED** [review]
Verifying, this was also what I did to make it work

**Comment by TiagoRechau** [comment]
Since it works fine, will this be merged?

**Comment by mnemanja** [comment]
@LukasBombach, would you mind addressing this pull request?

**Pull request merged**
