### PR TITLE
Add observedAttributes

### PR DESCRIPTION
**Pull request by amay0048**
To use `webComponentAttributeChanged` you need to provide `observedAttributes`

### CODE REVIEW

**Comment by amay0048** [comment]
Created a separate MR as I added style loading to my master as well.

**Comment by chfritz** [comment]
Hey @amay0048 , these suggested additions look great! Why did you close the PR? I saw you still have the commits in your [fork](https://github.com/amay0048/react-web-component). Did you publish your fork as an npm package by any chance?

PS: what's an MR?

**Comment by amay0048** [comment]
Hey @chfritz I can't remember why I closed this, I think I added another suggestion somewhere else. MR = PR in my head, even though they aren't quite the same 😅

**Comment by amay0048** [comment]
@chfritz I actually ended up rewriting my own implementation. I'll see if I can dig it up and publish it.

**Comment by amay0048** [comment]
@chfritz it ended up be simpler to just create a gist. There really isn't much going on, and several implementations can have different requirements so I hope this helps, adapt it as you need :-)

https://gist.github.com/amay0048/51de749f78020c95a600e4afc6c639d6

You can drop the shadow dom in like this if you need it: https://github.com/LukasBombach/react-web-component/blob/master/src/dev/index.js#L47

**Comment by chfritz** [comment]
Awesome, thanks @amay0048 !

**Pull request closed without merging**
