### PR TITLE
Add support for opting-out from shadowRoot behavior.

### PR DESCRIPTION
**Pull request by mnemanja**
**Improvements list:**
Babel has been added to the library so that we can utilize ES6 features. The library also now features **dev** version for debugging and **minified** one for the production.

Attributes passed on to the web component will be added to the React component's `props`.

* Added support for opting-out from shadowRoot behavior
* Transpile from ES6 to ES5
* Added type definition and dev dependencies
* Add .editorsconfig file
* Adjust the Readme.md
* Bump the version
* Support for the web component attributes

### CODE REVIEW

**Comment by mnemanja** [comment]
@LukasBombach here it is :)

**Comment by LukasBombach** [comment]
Ok this is a big one, I need some time to process this as I am also pretty busy with work right now. Is it ok for you if you use a local copy for now?

**Comment by LukasBombach** [comment]
Also: Thank you!

**Comment by mnemanja** [comment]
Yes, it is. Sorry about it :)

Not a problem. Have fun with it :)

**Comment by LukasBombach** [comment]
Well thank you for your work!

**Comment by LukasBombach** [comment]
Sorry @mnemanja I have a new position at work and it is super consuming, I still need a while to get back to this PR

**Comment by fbarbare** [comment]
Hi @LukasBombach 
Could we have an update on when this might go in?
Otherwise I'm gonna have to use the forked version too
Thanks

**Comment by LukasBombach** [comment]
Hey @fbarbare sorry I have no time to maintain this anymore, please go ahead and fork!

**Comment by fbarbare** [comment]
@LukasBombach Could you make me an owner of the NPM package then? So I can publish the updates and stuff?

**Comment by LukasBombach** [comment]
I need to check this with my old team at work. I did this as part of my job and I need to discuss with the others in my former team if they are ok with this. I will get back to you!

**Comment by LukasBombach** [comment]
(I just wrote to my team and will wait for answers)

**Comment by fbarbare** [comment]
Hi @LukasBombach ! Any news? 😃

**Comment by LukasBombach** [comment]
Hey @fbarbare yes! I actually got a reply from my former team today asking me about specifics. I have already answered them and now I am waiting for their reply

**Comment by fbarbare** [comment]
Hi @LukasBombach 
Pinging you again 😄

**Comment by LukasBombach** [comment]
My colleagues seem busy. You know what, I am going to merge this this weekend. Sorry for the long delay.

**Comment by fbarbare** [comment]
Hi @LukasBombach  Any news? 😄 Sorry for being a pain...

**Comment by LukasBombach** [comment]
Merged and published as `react-web-component@1.3.0`, I am truly sorry for the long wait

**Pull request merged**
